version: '3.7'
services:
  angular-app:
    build:
      context: ./to-do-list
    ports:
      - "4200:4200"
    volumes:
      - ./to-do-list:/app
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

